import axios from 'axios';

// Actions
const CREATE_DRIVER_PROCESS = "driver/CREATE_DRIVER_PROCESS";
const CREATE_DRIVER_SUCCESS = "driver/CREATE_DRIVER_SUCCESS";
const CREATE_DRIVER_ERROR = "driver/CREATE_DRIVER_ERROR";

const DELETE_DRIVER_PROCESS = "driver/DELETE_DRIVER_PROCESS";
const DELETE_DRIVER_SUCCESS = "driver/DELETE_DRIVER_SUCCESS";
const DELETE_DRIVER_ERROR = "driver/DELETE_DRIVER_ERROR";

// 



